"""
Provides geographical context mappings for NLP Geofencing.
"""

PINCODE_MAP = {
    "560030": {"neighborhood": "Adugodi", "city": "Bangalore", "state": "Karnataka"},
    "560034": {"neighborhood": "Agara", "city": "Bangalore", "state": "Karnataka"},
    "560007": {"neighborhood": "Agram", "city": "Bangalore", "state": "Karnataka"},
    "560092": {"neighborhood": "Amruthahalli", "city": "Bangalore", "state": "Karnataka"},
    "560024": {"neighborhood": "Anandnagar", "city": "Bangalore", "state": "Karnataka"},
    "562106": {"neighborhood": "Anekal", "city": "Bangalore", "state": "Karnataka"},
    "560045": {"neighborhood": "Arabic College", "city": "Bangalore", "state": "Karnataka"},
    "560003": {"neighborhood": "Aranya Bhavan", "city": "Bangalore", "state": "Karnataka"},
    "560050": {"neighborhood": "Ashoknagar", "city": "Bangalore", "state": "Karnataka"},
    "562107": {"neighborhood": "Attibele", "city": "Bangalore", "state": "Karnataka"},
    "560064": {"neighborhood": "Attur", "city": "Bangalore", "state": "Karnataka"},
    "560047": {"neighborhood": "Austin Town", "city": "Bangalore", "state": "Karnataka"},
    "560026": {"neighborhood": "Avalahalli", "city": "Bangalore", "state": "Karnataka"},
    "560086": {"neighborhood": "Avani Sringeri mutt", "city": "Bangalore", "state": "Karnataka"},
    "560002": {"neighborhood": "Avenue Road", "city": "Bangalore", "state": "Karnataka"},
    "560070": {"neighborhood": "B Sk ii stage", "city": "Bangalore", "state": "Karnataka"},
    "560073": {"neighborhood": "Bagalgunte", "city": "Bangalore", "state": "Karnataka"},
    "562149": {"neighborhood": "Bagalur", "city": "Bangalore", "state": "Karnataka"},
    "560053": {"neighborhood": "Balepete", "city": "Bangalore", "state": "Karnataka"},
    "560085": {"neighborhood": "Banashankari Iii stage", "city": "Bangalore", "state": "Karnataka"},
    "560043": {"neighborhood": "Banaswadi", "city": "Bangalore", "state": "Karnataka"},
    "560017": {"neighborhood": "Bangalore Air port", "city": "Bangalore", "state": "Karnataka"},
    "560001": {"neighborhood": "Bangalore Bazaar", "city": "Bangalore", "state": "Karnataka"},
    "560009": {"neighborhood": "Bangalore Dist offices bldg", "city": "Bangalore", "state": "Karnataka"},
    "560025": {"neighborhood": "Bangalore Sub fgn post", "city": "Bangalore", "state": "Karnataka"},
    "560083": {"neighborhood": "Bannerghatta", "city": "Bangalore", "state": "Karnataka"},
    "560076": {"neighborhood": "Bannerghatta Road", "city": "Bangalore", "state": "Karnataka"},
    "560004": {"neighborhood": "Basavanagudi", "city": "Bangalore", "state": "Karnataka"},
    "560079": {"neighborhood": "Basaveshwaranagar", "city": "Bangalore", "state": "Karnataka"},
    "560103": {"neighborhood": "Bellandur", "city": "Bangalore", "state": "Karnataka"},
    "560046": {"neighborhood": "Benson Town", "city": "Bangalore", "state": "Karnataka"},
    "562157": {"neighborhood": "Bettahalsur", "city": "Bangalore", "state": "Karnataka"},
    "560010": {"neighborhood": "Bhashyam Circle", "city": "Bangalore", "state": "Karnataka"},
    "560049": {"neighborhood": "Bhattarahalli", "city": "Bangalore", "state": "Karnataka"},
    "560056": {"neighborhood": "Bnagalore Viswavidalaya", "city": "Bangalore", "state": "Karnataka"},
    "560068": {"neighborhood": "Bommanahalli", "city": "Bangalore", "state": "Karnataka"},
    "560093": {"neighborhood": "C.V.raman nagar", "city": "Bangalore", "state": "Karnataka"},
    "560018": {"neighborhood": "Chamrajpet", "city": "Bangalore", "state": "Karnataka"},
    "560040": {"neighborhood": "Chandra Lay out", "city": "Bangalore", "state": "Karnataka"},
    "560097": {"neighborhood": "Chikkabettahalli", "city": "Bangalore", "state": "Karnataka"},
    "560061": {"neighborhood": "Chikkalasandra", "city": "Bangalore", "state": "Karnataka"},
    "562130": {"neighborhood": "Chikkanahalli", "city": "Bangalore", "state": "Karnataka"},
    "560067": {"neighborhood": "Devanagundi", "city": "Bangalore", "state": "Karnataka"},
    "560036": {"neighborhood": "Devasandra", "city": "Bangalore", "state": "Karnataka"},
    "560029": {"neighborhood": "Dharmaram College", "city": "Bangalore", "state": "Karnataka"},
    "560062": {"neighborhood": "Doddakallasandra", "city": "Bangalore", "state": "Karnataka"},
    "560037": {"neighborhood": "Doddanekkundi", "city": "Bangalore", "state": "Karnataka"},
    "560071": {"neighborhood": "Domlur", "city": "Bangalore", "state": "Karnataka"},
    "562125": {"neighborhood": "Dommasandra", "city": "Bangalore", "state": "Karnataka"},
    "560016": {"neighborhood": "Doorvaninagar", "city": "Bangalore", "state": "Karnataka"},
    "560100": {"neighborhood": "Electronics City", "city": "Bangalore", "state": "Karnataka"},
    "560005": {"neighborhood": "Fraser Town", "city": "Bangalore", "state": "Karnataka"},
    "560065": {"neighborhood": "G.K.v.k.", "city": "Bangalore", "state": "Karnataka"},
    "560019": {"neighborhood": "Gaviopuram Extension", "city": "Bangalore", "state": "Karnataka"},
    "560021": {"neighborhood": "Gayathrinagar", "city": "Bangalore", "state": "Karnataka"},
    "560022": {"neighborhood": "Goraguntepalya", "city": "Bangalore", "state": "Karnataka"},
    "560013": {"neighborhood": "Govindapalya", "city": "Bangalore", "state": "Karnataka"},
    "560087": {"neighborhood": "Gunjur", "city": "Bangalore", "state": "Karnataka"},
    "560008": {"neighborhood": "H.A.l ii stage", "city": "Bangalore", "state": "Karnataka"},
    "560051": {"neighborhood": "H.K.p. road", "city": "Bangalore", "state": "Karnataka"},
    "560102": {"neighborhood": "Hsr Layout", "city": "Bangalore", "state": "Karnataka"},
    "560104": {"neighborhood": "Hampinagar", "city": "Bangalore", "state": "Karnataka"},
    "560048": {"neighborhood": "Hoodi", "city": "Bangalore", "state": "Karnataka"},
    "560094": {"neighborhood": "Isro Anthariksha bhavan", "city": "Bangalore", "state": "Karnataka"},
    "560066": {"neighborhood": "Immedihalli", "city": "Bangalore", "state": "Karnataka"},
    "560038": {"neighborhood": "Indiranagar", "city": "Bangalore", "state": "Karnataka"},
    "560078": {"neighborhood": "J P nagar", "city": "Bangalore", "state": "Karnataka"},
    "560006": {"neighborhood": "J.C.nagar", "city": "Bangalore", "state": "Karnataka"},
    "560014": {"neighborhood": "Jalahalli East", "city": "Bangalore", "state": "Karnataka"},
    "560015": {"neighborhood": "Jalahalli West", "city": "Bangalore", "state": "Karnataka"},
    "560041": {"neighborhood": "Jayanagar", "city": "Bangalore", "state": "Karnataka"},
    "560069": {"neighborhood": "Jayangar East", "city": "Bangalore", "state": "Karnataka"},
    "560011": {"neighborhood": "Jayangar Iii block", "city": "Bangalore", "state": "Karnataka"},
    "560020": {"neighborhood": "K.P.west", "city": "Bangalore", "state": "Karnataka"},
    "560084": {"neighborhood": "Kacharakanahalli", "city": "Bangalore", "state": "Karnataka"},
    "560096": {"neighborhood": "Kanteeravanagar", "city": "Bangalore", "state": "Karnataka"},
    "560098": {"neighborhood": "Kenchanahalli", "city": "Bangalore", "state": "Karnataka"},
    "560095": {"neighborhood": "Koramangala Vi bk", "city": "Bangalore", "state": "Karnataka"},
    "560077": {"neighborhood": "Kothanur", "city": "Bangalore", "state": "Karnataka"},
    "560074": {"neighborhood": "Kumbalgodu", "city": "Bangalore", "state": "Karnataka"},
    "560054": {"neighborhood": "M S r road", "city": "Bangalore", "state": "Karnataka"},
    "560023": {"neighborhood": "Magadi Road", "city": "Bangalore", "state": "Karnataka"},
    "560033": {"neighborhood": "Malkand Lines", "city": "Bangalore", "state": "Karnataka"},
    "560055": {"neighborhood": "Malleswaram West", "city": "Bangalore", "state": "Karnataka"},
    "560099": {"neighborhood": "Muthanallur", "city": "Bangalore", "state": "Karnataka"},
    "560072": {"neighborhood": "Nagarbhavi", "city": "Bangalore", "state": "Karnataka"},
    "560039": {"neighborhood": "Nayandahalli", "city": "Bangalore", "state": "Karnataka"},
    "560075": {"neighborhood": "New Thippasandra", "city": "Bangalore", "state": "Karnataka"},
    "560032": {"neighborhood": "P&t Col. kavalbyrasandra", "city": "Bangalore", "state": "Karnataka"},
    "560058": {"neighborhood": "Peenya I stage", "city": "Bangalore", "state": "Karnataka"},
    "560059": {"neighborhood": "Rv Niketan", "city": "Bangalore", "state": "Karnataka"},
    "560080": {"neighborhood": "Sadashivanagar", "city": "Bangalore", "state": "Karnataka"},
    "560027": {"neighborhood": "Sampangiramnagar", "city": "Bangalore", "state": "Karnataka"},
    "560012": {"neighborhood": "Science Institute", "city": "Bangalore", "state": "Karnataka"},
    "560042": {"neighborhood": "Sivan Chetty gardens", "city": "Bangalore", "state": "Karnataka"},
    "560028": {"neighborhood": "Tyagrajnagar", "city": "Bangalore", "state": "Karnataka"},
    "560052": {"neighborhood": "Vasanthnagar", "city": "Bangalore", "state": "Karnataka"},
    "560091": {"neighborhood": "Viswaneedam", "city": "Bangalore", "state": "Karnataka"},
}

def get_location_context(pincode: str) -> dict:
    """Matches incoming pin codes with their text representation for AI news analysis."""
    return PINCODE_MAP.get(pincode, {"neighborhood": "Unknown", "city": "Bengaluru", "state": "Karnataka"})
